### PR TITLE
Did pr1

### PR DESCRIPTION
**Pull request by helewrer3**

### CODE REVIEW

**Comment by specdrake** [comment]
Try running it locally, you'll find a problem.

**Comment by specdrake** [comment]
Did you run it on your computer? (There's a runtime error)

**Comment by helewrer3** [comment]
Yes, I did run it locally it did not give me an error.
link for pr2 - https://ideone.com/jfSnk9
link for pr1 - https://ideone.com/rXBaBA

**Comment by specdrake** [comment]
https://www.onlinegdb.com/online_python_interpreter
Try here

**Comment by helewrer3** [comment]
Did the changes
pr 1 -> https://onlinegdb.com/Syb1gpK8I
pr 2 -> https://onlinegdb.com/HJpGx6Y8L

**Comment by specdrake** [comment]
Solve only one problem, either pr1 or pr2

**Pull request merged**
